### ISSUE TITLE
the project does not build properly

### ISSUE THREAD

**Issue by kriskate** [estshorter/m5paper-dashboard#1]
Hello, I found you project interesting but unfortunatelly it doesn't build for me. I keep getting this error:

```
Linking .pio/build/m5paper/firmware.elf
/Users/ddd/.platformio/packages/toolchain-xtensa32/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
*** [.pio/build/m5paper/firmware.elf] Error 1
======================================================== [FAILED] Took 29.82 seconds ==============
```

Any ideas?
Thanks!

**Comment by estshorter** [comment]
I can reproduce this and stopped using the latest toolchain-xtensa32 and framework-arduinoespressif32 in https://github.com/estshorter/m5paper-dashboard/commit/5fdf3265d1f29cc715b9d0f3fcf0c7f74ddf4cc3.

Would you try https://github.com/estshorter/m5paper-dashboard/commit/5fdf3265d1f29cc715b9d0f3fcf0c7f74ddf4cc3 ?

**Comment by estshorter** [comment]
Note: this error is related to https://github.com/espressif/arduino-esp32/issues/5436, and can be solved by https://github.com/espressif/arduino-esp32/issues/5436#issuecomment-885487369.

**Comment by kriskate** [comment]
thanks! it works now, uploaded to m5paper 💯 
I also had to comment these out:
```
; upload_protocol = espota
; upload_port = 192.168.10.106
```
I have to play around with OTA on esp :)

cool project!
